Update README.md
ProjectPythia/pythia-tutorials pull request #1
Opened 2021-11-01 20:10 UTC by jukent

First pass at updating the README for the tutorial content repository.

Some to do steps hinted at:
- Create a fleshed out contributor's guide
- Create a notebook and md template

Do we want the document tree to be updated here with tutorials or to have a separate file (perhaps a README in the tutorials directory) that lists all tutorials.

2021-11-01 20:59 UTC, mgrover1 requested changes
Looks good - just a few minor changes

2021-11-01 20:59 UTC, mgrover1 commented on README.md
> +We, the Pythia team, want there to be a low barrier to entry for the tutorial speaker to develop and host their tutorial content in this repository. For the speaker's convenience we will provide a si
perhaps change "want there to be a low barrier to entry for the tutorial speaker" to "we want to lower the barrier of entry for the tutorial speaker"?

2021-11-01 20:59 UTC, mgrover1 commented on README.md
> +- Within the `tutorials` direcotry there is a unique directory for every tutorial and a `template` directory, containing a markdown and a notebook template (coming soon).
Watch the spelling of "directory"

2021-11-01 20:59 UTC, mgrover1 commented on README.md
> +- Each tutorial is named with its topic and date with the format `TOPIC_YYYY_MM_DD`.
Provide an example here (ex. `pandas_2021_08_03`)

2021-11-02 00:29 UTC, clyne approved these changes
Looks great, Julia! Thanks for doing this.

2021-11-02 16:34 UTC, mgrover1 approved these changes
Looks great! Thanks @jukent

2021-11-02 16:44 UTC, merged